# Generated by Django 3.2 on 2021-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
