# Generated by Django 3.2 on 2021-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_average_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_ratings',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
